### ISSUE TITLE
Appears to not work under Qt5

### ISSUE THREAD

**Issue by raelgc** [QupZilla/qtwebkit-plugins#7]
I've built this library for Qt4 and Qt5 under Ubuntu 64 bits, saving the code in 2 different folders, and built the `Make` file using the respective `qmake` version.

Then, I ran `make` and `sudo make install` for each one and got the library installed in proper places:
- Qt4: `/usr/lib/x86_64-linux-gnu/qt4/plugins/webkit/libqtwebkitplugins.so`
- Qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/webkit/libqtwebkitplugins.so`

Then I tested in some QWebView examples, but only the Qt4 version worked fine.

I've created this simple example to check if the `hunspell` output will be printed, first for Qt4:

``` python
#!/usr/bin/env python3
import sys
from PyQt4.QtGui import QApplication
from PyQt4.QtCore import QUrl
from PyQt4.QtWebKit import QWebView

if __name__ == '__main__':
    app = QApplication(sys.argv)
    view = QWebView()
    view.load(QUrl('http://www.google.com'))
    app.exec_()
```

and the same version for Qt5:

``` python
#!/usr/bin/env python3
import sys
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QUrl
from PyQt5.QtWebKitWidgets import QWebView

if __name__ == '__main__':
    app = QApplication(sys.argv)
    view = QWebView()
    view.load(QUrl('http://www.google.com'))
    app.exec_()
```

But only the Qt4 version produces the `hunspell` start output and proper red marking under misspelled words:

``` term
SpellCheck: Language = "en_US"
```

**Comment by raelgc** [comment]
I even tried this: http://stackoverflow.com/a/28924656/1604312

> For this work in QT-5.2+ is necessary to modified the qwebkitplatformplugin.h file
> 
> Change this:
> 
> QT_BEGIN_NAMESPACE
> Q_DECLARE_INTERFACE(QWebKitPlatformPlugin, "com.nokia.Qt.WebKit.PlatformPlugin/1.9");
> 
> By this:
> 
> QT_BEGIN_NAMESPACE
> Q_DECLARE_INTERFACE(QWebKitPlatformPlugin,
>     "org.qt-project.Qt.WebKit.PlatformPlugin/1.9");

**Comment by itohnobue** [comment]
@raelgc Just for you to know: I was able to compile and make it work for Windows with PyQt 5.4.1 + Qt 5.4.1 + hunspell 1.3.3 and currently I'm trying to do the same for OS X.

Please note that the only thing I need from this library is a spell checker so I removed notifications plugin completely to avoid additional problems during the compilation.

Regarding your problem:

1. Your example lack one important option which need to be set so QWebKit would load the plugin  (this can also be done for specific QWebView instead of using the global settings):

```python
from PyQt5.QtWebKit import QWebSettings
settings = QWebSettings.globalSettings()
settings.setAttribute(QWebSettings.PluginsEnabled, True)
```

2. Try to check your **libqtwebkitplugins.so** file with **ldd** and make sure that you have proper hunspell library installed (it should be visible in dependencies list with full path).

3. Check that hunspell itself works properly and has access to the default dictionary (which means that dictionary language is set with **DICTIONARY** environment variable and path to the directory with dictionary files is set with **DICTPATH**).

Hope it helps :)

**Comment by The-Compiler** [comment]
> 1) Your example lack one important option which need to be set so QWebKit would load the plugin (this can also be done for specific QWebView instead of using the global settings)

Are you sure that's actually related to this plugins? From my understanding of that setting, it applies to NPAPI plugins like flash, but QtWebKit Qt plugins shouldn't be affected by it.

**Comment by raelgc** [comment]
Thank you @itohnobue, I'll try tip 2 and 3.

For 1, like @The-Compiler said, it's related to browser plugins, not to QtWebkit plugins.

**Comment by raelgc** [comment]
My environment: 

```term
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
```

Output of `qtchooser -print-env`:
```term
QT_SELECT="default"
QTTOOLDIR="/usr/lib/x86_64-linux-gnu/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu"
```
Dictionaries are properly configured, as it's working with the `Qt4` version.

**Comment by brcontainer** [comment]
@raelgc 

> I even tried this: http://stackoverflow.com/a/28924656/1604312

If your QT5 use `com.nokia.Qt.WebKit.PlatformPlugin/1.9`, then it means that somehow you mixed QT4 with QT5. Solution in link, posted by me, is used for old version of `QupZilla/qtwebkit-plugins`, I recommend completely remove the QT 4 and 5. After install QT5 only.

- You used `make` command or Build button (Ctrl+b) in QT Design (QT5) or compile button (ctrl+r)?
- Environment variables are pointing to the QT5? Because if not it will not work.
- Your project is compiled in Release or Debug mode?

Try this:

 - Compile in QT5 for create .so (using Release mode and not Debug) or use `make install`
 - Create in your project folder a folder named `webkit` and put your `qtwebkitplugins.so`  into, like this `/home/project/webkit/qtwebkitplugins.so`
- Run your python application

**Comment by raelgc** [comment]
Hi @brcontainer, for some reason I lost your post. To answer your questions:

* I'm using `make`
* My `qmake --version` is answering `Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu`
* I'm using `make install`

The commit #61648ba from @nowrep didn't change the behavior. That header was already present in my attempt.

**Comment by nowrep** [comment]
Header was present, but `moc` wasn't being run on it and thus QObject structures were not built resulting in unresolved symbols when loading plugin.

You should do clear rebuild and make sure that `build/moc_qwebkitplugin.h` is created.

**Comment by nowrep** [comment]
No additional steps are required, if you use the same `qmake` (eg. Qt install) that was used for building PyQt then you just do `qmake && make && make install` and it should work.

If not, you should make sure that the QtWebKit is trying to load the plugin (eg. with `strace`). And if it is trying, but it can't load it, then try to manually load it with `QPluginLoader` and inspect the error message.

**Comment by raelgc** [comment]
@nowrep Thank you for all the tips! Really valuable ones! I'll try them!
